on:
  pull_request:
    paths:
    - src/Dockerfile

name: Docker scan

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: ${{ github.repository }}:${{ github.sha }}

    - name: Scan Docker image
      uses: anchore/scan-action@v1
      id: anchore-scan
      with:
        image-reference: ${{ github.repository }}:${{ github.sha }}
        fail-build: true
