on:
  schedule:
  - cron: '0 0 * * MON'

name: Docker scan cronjob

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: ${{ github.repository }}:${{ github.sha }}

    - name: Scan Docker image
      uses: anchore/scan-action@v1
      id: anchore-scan
      with:
        image-reference: ${{ github.repository }}:${{ github.sha }}

    - name: Find new vulnerabilities
      uses: bluedrop-learning-networks/bln-ci-uniq-issue-action@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        command: report-vulnerabilities
        vulnerabilities-file-path: ./anchore-reports/vulnerabilities.json
        vulnerabilities-output-path: ./anchore-reports/vulnerabilities_to_report.json

    - name: Parse new vulnerabilities
      run: |
        VULNERABILITIES=$(cat ./anchore-reports/vulnerabilities_to_report.json | jq '.vulnerabilities | length')
        echo "vulnerabilities=$VULNERABILITIES" >> $GITHUB_ENV

    - name: Add vulnerability data to the issue template
      if: env.vulnerabilities > 0
      run: |
        echo "\`\`\`" >> ./.github/VULNERABILITY_TEMPLATE.md
        cat ./anchore-reports/vulnerabilities_to_report.json >> ./.github/VULNERABILITY_TEMPLATE.md
        echo "\`\`\`" >> ./.github/VULNERABILITY_TEMPLATE.md

    - name: Create issue if vulnerabilities exist
      uses: JasonEtco/create-an-issue@master
      if: env.vulnerabilities > 0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        filename: .github/VULNERABILITY_TEMPLATE.md
