name: Publish Docker Image

on:
  push:
    branches:
    - master
    - deploy-*

jobs:

  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Preparation
      id: prep
      run: |
        TAGS="${GITHUB_SHA}"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="${GITHUB_SHA},latest"
        fi
        echo ::set-output name=tags::${TAGS}

    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        repository: ${{ github.repository }}/${{ github.event.repository.name }}
        tags: ${{ steps.prep.outputs.tags }}

  notify:
    name: Notify Ops Planner
    runs-on: ubuntu-latest
    needs: publish
    steps:

    - name: Notify Ops Planner
      run: |
        echo notify ops-planner of publish
