name: Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 8

    - run: |
        npm ci
        npm run test
